# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-18 11:56
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proprietary1', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('proprietary2', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('proprietary3', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('proprietary4', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('gpl', models.IntegerField(default=59, validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('proprietaryTurn', models.BooleanField(default=True)),
                ('gplUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_gplUsers', to=settings.AUTH_USER_MODEL)),
                ('proprietaryUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_proprietaryUsers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('target', models.IntegerField(validators=[django.core.validators.MaxValueValidator(63), django.core.validators.MinValueValidator(0)])),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_games', to='server.Game')),
            ],
        ),
    ]
